name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Gulp globally
        run: npm install --global gulp-cli

      - name: Install dependencies
        run: npm install

      - name: Run Gulp to build
        run: gulp build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --local user.email "soulaimaneyh07@gmail.com"
          git config --local user.name "Soulaimane Yahya"
          git add assets/css
          git commit -m "Deploy CSS files"
          git push origin main
